# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple_deployer}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Kononov"]
  s.date = %q{2011-01-06}
  s.default_executable = %q{sd}
  s.description = %q{Appoxy simple_deployer Gem}
  s.email = %q{roman@appoxy.com}
  s.executables = ["sd"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
    "Rakefile",
    "VERSION.yml",
    "bin/sd",
    "lib/simple_deployr.rb",
    "lib/simple_deployr/client.rb",
    "lib/simple_deployr/command.rb",
    "lib/simple_deployr/commands/base.rb",
    "lib/simple_deployr/commands/help.rb",
    "lib/simple_deployr/commands/info.rb",
    "lib/simple_deployr/commands/project.rb",
    "lib/simple_deployr/commands/projects.rb",
    "lib/simple_deployr/commands/server.rb",
    "lib/simple_deployr/config.rb",
    "simple_deployer.gemspec"
  ]
  s.homepage = %q{http://www.simpledeployer.com}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Appoxy simple_deployer Gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws>, [">= 0"])
      s.add_runtime_dependency(%q<zip>, [">= 0"])
      s.add_runtime_dependency(%q<appoxy_rails>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<aws>, [">= 0"])
      s.add_dependency(%q<zip>, [">= 0"])
      s.add_dependency(%q<appoxy_rails>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<aws>, [">= 0"])
    s.add_dependency(%q<zip>, [">= 0"])
    s.add_dependency(%q<appoxy_rails>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

